apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - image: nginx
        name: nginx
